### ISSUE TITLE
TypeError: Object.observe is not a function

### ISSUE THREAD

**Issue by rozaq14996** [webofthings/webofthings.js#9] opened 2017-09-23 08:08 UTC
TypeError: Object.observe is not a function
    at d:\Project\webofthings.js-master\plugins\corePlugin.js:68:12
    at arrayEach (d:\Project\webofthings.js-master\node_modules\lodash\internal\arrayEach.js:15:9)
    at Object.<anonymous> (d:\Project\webofthings.js-master\node_modules\lodash\internal\createForEach.js:15:9)
    at exports.LedsPlugin.CorePlugin.observeActions (d:\Project\webofthings.js-master\plugins\corePlugin.js:67:5)
    at exports.LedsPlugin.CorePlugin.start (d:\Project\webofthings.js-master\plugins\corePlugin.js:30:26)
    at initPlugins (d:\Project\webofthings.js-master\wot-server.js:50:14)
    at createServer (d:\Project\webofthings.js-master\wot-server.js:12:3)
    at Object.<anonymous> (d:\Project\webofthings.js-master\wot.js:2:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webofthings@0.1.0 start: `node wot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webofthings@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by domguinard** [comment] 2017-09-23 11:33
Duplicate of #3 the current fix is to make sure you use version 4.X of Node.

**Closed by domguinard** 2017-09-23 11:33 UTC
